= Jump The Queue
====
In this scenario you will use "Jump The Queue" for the first time.

The first step is to start the server.

In the second step you will build and use the app.

Please remember this is only a development setup and not for productive usage!!!

You can find the source code for the "Jump The Queue" tutorial application here:

https://github.com/devonfw/jump-the-queue

And you can find the documentation here:

https://github.com/devonfw/jump-the-queue/wiki
====

Clone the Jump The Queue repository. You can find it on https://github.com/devonfw/jump-the-queue.
[step]
--
cloneRepository("", "https://github.com/devonfw/jump-the-queue.git")
--

The next step is to build the java project within the Jump The Queue repository.
[step]
--
buildJava("jump-the-queue/java/jtqj")
--

Start the java backend server.
[step]
--
runServerJava("jump-the-queue/java/jtqj/server", { "startupTime": 50, "port": 8081, "path": "jumpthequeue" })
--

Install the dependencies of the angular project.
[step]
--
npmInstall("jump-the-queue/angular")
--

Change the url to the backend server
[step]
--
changeFile("jump-the-queue/angular/src/environments/environment.ts", { "fileConsole": "files/environmentConsole.ts", "fileKatacoda": "files/environmentKatacoda.ts" })
--

Run the frontend server.
[step]
--
runClientNg("jump-the-queue/angular", { "startupTime": 150, "port": 4200, "path": "" })
--
