openapi: 3.0.0
servers:
  - url: 'https://localhost:8081/server/services/rest'
    description: Just some data
info:
  title: devonfw Example
  description: Example of a API definition
  version: 1.0.0
  x-rootpackage: com.devonfw.poc.jwtsample
paths:
  /:
    post:
      responses:
        '200':
          description: Any
components:
    schemas:
        User:
          x-component: usermanagement
          description: Entity definiton of User
          type: object
          properties:
            name:
              type: string
              maxLength: 100
              uniqueItems: true            
            age:
              type: integer
            phone :
              type: string
              maxLength: 100
              uniqueItems: true
            email:
              type: string
              maxLength: 100
              uniqueItems: true              
          required:
            - name
            - email