= Try Jump The Queue 
==== 
In this scenario you will use "Jump The Queue" for the first time.

The first step is to start the server.

In the second step you will build and use the app.

!! Please remember this is only a development setup and not for productive usage! !!

You can find the source code for the "Jump The Queue" tutorial application here:

https://github.com/devonfw/jump-the-queue

And you can find the documentation here:

https://github.com/devonfw/jump-the-queue/wiki
====

Okay let's start!

[step]
--
restoreDevonfwIde(["java","mvn","npm","ng"])
--


[step]
--
cloneRepository("", "https://github.com/devonfw/jump-the-queue.git")
--

[step]
--
buildJava("jump-the-queue/java/jtqj", true)
--

Wait until you see the message "BUILD SUCCESS".

[step]
--
runServerJava("jump-the-queue/java/jtqj/server", { "startupTime": 40, "port": 8081, "path": "jumpthequeue" })
--

[step]
--
npmInstall("jump-the-queue/angular")
--

The following two steps are only needed in this tutorial. Normally you can simply execute "ng serve", open the https://localhost:4200/ and start using the app.

[step]
--
changeFile("jump-the-queue/angular/src/environments/environment.ts", { "file": "placeholder.txt", "placeholder": " baseUrlRestServices: 'http://localhost:8081/jumpthequeue/services/rest'," })
--

[step]
--
runClientNg("jump-the-queue/angular", { "startupTime": 200, "port": 4200, "path": "" })
--