= Migrate a devon4j project to the latest version
====
This tutorial mainly focuses on migrating an old version of devon4j project to the latest version.
The devonfw provides various commandlet allowing user to setup Java environment. It supports devon4j. The arguments (devon java «args») are explained by the below details: 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.

====


[step]
--
restoreDevonfwIde(["java","vscode"], "2020.08.001")
--

====
Now, To navigate inside devonfw-ide installations execute below command.
[step]
== Create devon4j sample project
--
changeWorkspace("devonfw/workspaces/main") 
--
Now, we will create a sample devon4j application with the name *migrateSampleApp* and build it.
Now, Copy below command and execute it in the terminal.
`devon mvn archetype:generate -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server -DinteractiveMode=false -Dpackage=com.devonfw.example -DartifactId=migrateSampleApp -DgroupId=com.devonfw.example -Dversion=1.0.0-SNAPSHOT -DarchetypeVersion=2020.08.001`
====


Now, you have to change properties files inside core to remove special character which might give the error while migration.
[step]
== Change properties file
--
changeWorkspace("migrateSampleApp")
changeFile("migrateSampleApp/core/pom.xml", { "file": "files/pom.xml" })
--

In the below step it will execute "devon java migrate". This command will migrate devon4j project to latest version.
[step]
== Migrate devon4j to latest version
--
executeCommand("devon java migrate", "devon java migrate", {})
--


====
## Conclusion
You have successfully migrated an older version of devon4j project to latest version using command line.
====
