= Migrate a devon4j project to the latest version
====
This tutorial mainly focuses on migrating an older version of devon4j project to the latest version using devon4j migrate command.


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.
====

[step]
--
restoreDevonfwIde(["java","vscode"])
--

To demonstrate devon4j migrate we would need a sample devon4j project with an older version, which is already created for you. You just need to clone the repository.

To clone repository you should be inside devonfw-ide installed directory. 

Follow below step to do so.
[step]
== Clone the sample application
--
cloneRepository("", "https://github.com/devonfw-sample/devon4j-app-4tutorial.git")
--

====
Execute below command for project migration from  an older version to the latest version.
[step]
== Execute Migrate Command
--
executeCommand("cd devon4j-app-4tutorial", "cd devon4j-app-4tutorial")
executeCommand("devon java migrate", "devon java migrate")
--
You will see the message similar to the one below in command line along with different series of versions migrated, if project migrated successfully.
`Successfully applied 4 migrations to migrate project from version devon4j:2020.08.001 to devon4j:2021.04.002.`
====



====
## Conclusion
You have successfully migrated the sample project from an older version to the latest version using command line!!

For more details on devon4j java commands for various functionalities and the arguments (devon java «args») follow 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc
====
