= Migrate a devon4j project to the latest version
====
This tutorial mainly focuses on migrating an old version of devon4j project to the latest version.
The devonfw provides various commandlet allowing user to setup Java environment. It supports devon4j. The arguments (devon java «args») are explained by the below details: 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.

====


[step]
--
restoreDevonfwIde(["java","vscode"], "2020.08.001")
--


====
Now, we will create a sample devon4j application with the name *migrateSampleApp* and build it.
Now, Copy below command.
`devon mvn archetype:generate -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server -DinteractiveMode=false -Dpackage=com.devonfw.example -DartifactId=migrateSampleApp -DgroupId=com.devonfw.example -Dversion=1.0.0-SNAPSHOT -DarchetypeVersion=2020.08.001`
Paste it in the terminal and press enter to execute it.
[step]
== Create devon4j sample
--
changeFile("sampleapp/core/pom.xml", {"file": "files/pom.xml"})
--
devon4j sample project created successfully!!
====

In the below step it will execute "devon java migrate". This command will migrate devon4j project to latest version.
[step]
== Migrate devon4j to latest version
--
executeCommand("devon java migrate", "devon java migrate", {"dir": "sampleapp"})
--


====
## Conclusion
You have successfully migrated an older version of devon4j project to latest version using command line.
====
