= Migrate a devon4j project to the latest version
====
This tutorial mainly focuses on migrating an old version of devon4j project to the latest version.
The devonfw provides various commandlet allowing user to setup Java environment. It supports devon4j.

The arguments (devon java «args») are explained by the below details: 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.

====


Install older version of devonfw ( "2020.08.001")
[step]
--
restoreDevonfwIde(["java","mvn"])
--

Now, we will create a sample devon4j application with the name *sampleapp*.
[step]
--
executeCommand("mvn -DarchetypeVersion=3.0.1 -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate", "mvn -DarchetypeVersion=3.0.1 -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate", {"args":["-DgroupId=com.example.application", "-DartifactId=sampleapp", "-Dversion=1.0.0-SNAPSHOT", "-Dpackage=com.devonfw.application.sampleapp", "-DinteractiveMode=false", "-DarchetypeVersion=2020.08.001"] })
--

Now, you have to change properties files inside core to remove special character which might give error while migration.
[step]
== Change properties file
--
changeFile("sampleapp/core/pom.xml", { "file": "files/pom.xml" })
--

In the below step it will execute "devon java migrate".
[step]
--
executeCommand("devon java migrate", "devon java migrate", {"dir": "sampleapp"})
--


====
## Conclusion

In this tutorial you have learnt How to migrate an older version of devon4j project to the latest version using command line.

====
