=devon4j migrate

====
devon4j is the Java stack of devonfw.The java commandlet allows to install and setup Java. Also it supports devon4j.
## Prerequisites
* User should have Java development experience
## Learnig goals
After completing this scenario, you will have learned devon4j automatic migration using java migrate.
More information about devon4j migrate https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc.
====



[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--


create a new Java project based on devon4j application template. If a single argument is provided, this is the package name and is automatically split into groupId and artifactId. Use -DdbType=«db» to choose the database (hana, oracle, mssql, postgresql, mariadb, mysql, h2, hsqldb). Any option starting with dash is passed as is."
[step]
--
createDevon4jProject("com.example.application.sampleapp")
--

### migrate a devon4j project to the latest version. If for some reasons the current devonfw version (e.g. oasp4j:2.6.0) can not be auto-detected you may provide it manually after the 'from' argument. Also the 'single' option allows to migrate only to the next available version."


generate cicd files for the currect devon4java project
[step]
--
createFile("com.example.application.sampleapp/file.cicd")
--

====
## Conlusion
In this tutorial you have learnt how to migrate a devon4j application using java migrate.
====