= Migrate a devon4j project to the latest version
====
This tutorial mainly focuses on migrating an older version of devon4j project to the latest version using devon4j migrate command.


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.
====

[step]
--
restoreDevonfwIde(["java","vscode"])
--

To demonstrate devon4j migrate we would need a sample devon4j project with an older version, which is already created for you. You just need to clone the repository.

To clone repository you should be inside devonfw-ide installed directory. 
Follow bellow step to do so.
[step]
== Clone the sample application
--
cloneRepository("", "https://github.com/devonfw-sample/devon4j-app-4tutorial.git")
--

Execute below command for project migration from  an older version to the latest version.
[step]
== Execute Migrate Command
--
executeCommand("cd devon4j-app-4tutorial", "cd devon4j-app-4tutorial")
executeCommand("devon java migrate", "devon java migrate")
--


====
## Conclusion
You have successfully migrated the sample project from an older version to the lates version using command line!!

For more details on devon4j java commands for various functionalities and the arguments (devon java «args») follow 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc
====
