= Migrate a devon4j project to the latest version

[tags]
--
difficulty=beginner
topic=migration;version
asset=devon4j
--

====
This tutorial mainly focuses on migrating an older version of devon4j project to the latest version using devon4j migrate command.


## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.
====

[step]
--
restoreDevonfwIde(["java","vscode"])
--


[step]
--
restoreWorkspace({"workspace": "devon4j-migrate"})
--

====
To demonstrate devon4j migrate you would need a sample devon4j project with any older version. Here, we have already created a project with an older version i.e. 2020.08.001 for you. 

It is already cloned in workspace.

Execute below command for project migration from an older version to the latest version.
[step]
== Execute Migrate Command
--
executeCommand("devon java migrate", "devon java migrate", {"dir" : "devon4j-app-4tutorial"})
--
You will see the message similar to the one below, if project migrated successfully.
`Successfully applied 4 migrations to migrate project from version devon4j:2020.08.001 to devon4j:2021.04.002.`

Here, 2020.08.001 is the devon4j's older version and 2021.04.002 is devon4j's latest version.

====



====
## Conclusion
You have successfully migrated the sample project from an older version to the latest version using command line!!

For more details on devon4j java commands for various functionalities and the arguments (devon java «args») follow 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc
====
