= Migrate a devon4j project to the latest version
====
The java commandlet allows to setup Java. Also it supports devon4j. The arguments (devon java «args») are explained by the below details: 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc

This tutorial mainly focuses on to migrate an old version of devon4j project to the latest version.
## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.

====

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--

Note: devonfw IDE is already installed.
Now, we will create a sample devon4j application with the name *sampleapp* and build it.
Now, Copy below command and press enter to create devon4j project with older version i.e. "2020.08.001":
`devon mvn archetype:generate -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server -DinteractiveMode=false -Dpackage=olderversion -DartifactId=olderversionapp -DgroupId=olderversion -Dversion=1.0.0-SNAPSHOT -DarchetypeVersion=2020.08.001`
[step]
== Create and build devon4j project
--
changeFile("sampleapp/core/pom.xml", {"file": "files/pom.xml"})
--


In the below step it will execute "devon java migrate". This command will migrate devon4j project to latest version.
[step]
== Migrate devon4j to latest version
--
executeCommand("devon java migrate", "devon java migrate", {})
--


====
## Conclusion
You have successfully migrated an older version of devon4j project to latest version using command line.
====
