= Develop a devon4j HTTP REST Client service using Synchronous call
====
REST (REpresentational State Transfer) is an inter-operable protocol for services that is more lightweight than SOAP. We give best practices that lead to simple, easy and pragmatic "HTTP APIs".

## Prerequisites
* User should have development experience in JAVA.
* Basic knowledge of REST.

## Learning Goal
Here in this tutorial you will learn the following things:
* JAX-RS standard for REST service implementation proposed by devonfw.
* How to create REST client with devon4j using Synchronous call.

Let's get started!!
====

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--

====
* REST (REpresentational State Transfer) is an inter-operable protocol for services that is more lightweight than SOAP.
[step]
--
nextKatacodaStep("REST", [{ "file": "files/RestDescription.txt" }])
--
For more details on REST visit https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-rest.asciidoc

For more details on devon4j Service Client https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-service-client.asciidoc
====

====
As explained in REST document, With JAX-RS it is important to make sure that each service method is annotated with the proper HTTP method.

Let's create devon4j server.
[step]
== Create the devon4j-HTTP-REST-SERVER
--
createDevon4jProject("com.example.application.httprestserver")
buildJava("httprestserver", false)
createFolder("httprestserver/core/src/main/java/com/example/application/httprestserver/visitormanagement/service/api/rest")
createFile("httprestserver/api/src/main/java/com/example/application/httprestserver/visitormanagement/service/api/rest/VisitormanagementRestService.java", { "file": "files/VisitormanagementRestService.java" })
createFolder("httprestserver/core/src/main/java/com/example/application/httprestserver/visitormanagement/service/impl/rest")
createFile("httprestserver/core/src/main/java/com/example/application/httprestserver/visitormanagement/service/impl/rest/VisitormanagementRestServiceImpl.java", { "file": "files/VisitormanagementRestServiceImpl.java" })
changeFile("httprestserver/core/src/main/java/com/example/application/httprestserver/general/service/impl/config/BaseWebSecurityConfig.java", { "file": "files/BaseWebSecurityConfig.txt" })
--
* In above example we have created VisitormanagementRestService and it's implementation i.e. VisitormanagementRestServiceImpl using JAX-RS standard.
* Here, "VisitormanagementRestServiceImpl.java" is annotated with @Named to make it a spring-bean.
* To get return response to client "returnResponseToClient()" can be accessed via HTTP GET under the URL path "/visitormanagement/v1/clientrequest". It will return its result (String) as JSON (see @Produces in VisitormanagementRestService). 

Now, Java server should be running.
Now, You have to create devon4j service Client.
====

====
* To create devon4j service Client. First You need to create a sample devon4j project and build the project.
[step]
== Create devon4j service Client
--
createDevon4jProject("com.sample.application.httprestclient")
--

Then, You need to add required dependency to your application. 
====


[step]
--
nextKatacodaStep("  ", [{ "file": "files/dependency.txt" }])
--

====
You already have a Java interface VisitormanagementRestService to invoke.
You have to create rest client i.e. Devon4jRestClient.java and it's implementation class.
[step]
== Create devon4j rest client
--
createFile("httprestclient/api/src/main/java/com/sample/application/httprestclient/Devon4jRestClient.java", "files/Devon4jRestClient.java")
createFile("httprestclient/core/src/main/java/com/sample/application/httprestclient/Devon4jRestClientImpl.java", "files/Devon4jRestClientImpl.java")
nextKatacodaStep(" ", [{ "file": "files/explainSynchronousCall.txt" }])
--
After getting response, you can handle the response in your implementation. Here you can see that response is getting handled in "showResponse" method.
====


====
## Configuration 
An application needs to be configurable in order to allow internal setup but also to allow externalized configuration of a deployed package (e.g. integration into runtime environment). 
[step]
--
changeFile("httprestclient/core/src/main/resources/config/application.properties", { "file": "files/config_application.txt" })
buildJava("httprestclient", false)
nextKatacodaStep("Properties Configuration", [{ "file": "files/configurationProperties.txt" }])
--

Now, after configuration you have to start the client application.
====

====
This might take some time for application to start.
[step]
--
runServerJava("devonfw/workspaces/main/httprestclient/server", { "startupTime": 40, "port": 8081, "path": "httprestclient" })
--
Once the REST-server started running,
Open http://localhost:8080/client/services/rest/testrest/v1/response, Enter username as "admin" and password as "admin"
====