= Learn new pattern of REST APIs proposed by devonfw
== Different, new and easiest way to learn various methods and protocols of REST APIs proposed by devonfw. Which includes Exception handling, Testing, Security, etc.
====
REST (REpresentational State Transfer) is an inter-operable protocol for services that is more lightweight than SOAP. We give best practices that lead to simple, easy and pragmatic "HTTP APIs".

## Prerequisites
* devonfw IDE
* User should have development experience in JAVA.
* Basic knowledge of REST Services

## Learning Goal
Here in this tutorial you will learn the following things proposed by devonfw:
* REST urls format
* HTTP methods
* HTTP status codes 
* Metadata invoked in REST services
* JAX-RS standard for REST service implementation
* REST Exception Handling
* Recommendations for REST requests and responses: a deviation from common REST pattern		
* REST media types
* REST testing
* Security 

Let's get started
====

devonfw IDE has been installed for you.

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--