= Tutorial Compiler 
==== 
In this scenario you will use the tutorial-compiler to generate the cobigen tutorial.

The first part will be to setup your workspace.

Afterwards we will show you, how to write your own tutorials using an asciidoc.

You can find the documentation here:

https://github.com/devonfw-forge/tutorial-compiler/wiki

====

Let's start!

First of all, go to the tutorial-compiler repository on github:

https://github.com/devonfw-forge/tutorial-compiler

[step]
--
nextKatacodaStep("Fork the 'tutorial-compiler'-repository", "images/fork.jpg");
--

[step]
--
buildJava("jump-the-queue/java/jtqj", true)
--

Wait until you see the message "BUILD SUCCESS".

[step]
--
runServerJava("jump-the-queue/java/jtqj/server", { "startupTime": 40, "port": 8081, "path": "jumpthequeue" })
--

[step]
--
npmInstall("jump-the-queue/angular")
--

The following two steps are only needed in this tutorial. Normally you can simply execute "ng serve", open the https://localhost:4200/ and start using the app.

[step]
--
changeFile("jump-the-queue/angular/src/environments/environment.ts", { "file": "placeholder.txt", "placeholder": "http://localhost:8081/jumpthequeue/services/rest" })
--

[step]
--
runClientNg("jump-the-queue/angular", { "startupTime": 200, "port": 4200, "path": "" })
--