= Tutorial Compiler 
==== 
In this scenario you will use the tutorial-compiler to generate the "my-thai-star" tutorial.

The first part will be to setup your workspace.

Afterwards we will show you, how to write your own tutorials using an asciidoc.

Requirements: 
 * github-account

You can find the documentation here:

https://github.com/devonfw-forge/tutorial-compiler/wiki

====

====
# Setup your workspace
Let's start!

First of all, go to the tutorial-compiler repository on github:

https://github.com/devonfw-tutorials/tutorial-compiler

[step]
--
nextKatacodaStep("Fork the 'tutorial-compiler'-repository", [{ "image": "images/fork.jpg" }])
--

Fork the repository by clicking on the fork-button.
====

====
Go to your repositories, click on 'tutorial-compiler' and copy the repository Url as shown in image below.

[step]
--
nextKatacodaStep("Copy the 'tutorial-compiler'-URL", [{ "image": "images/clone_code.jpg" }])
--

====

====
Usually you would paste the copied URLs next to the 'git clone' - command, but in this tutorial we will clone the original 'tutorial-compiler'-repository. Therefore we are able to write the asciidoc-files and generate the tutorials, but we can not push changes in the source code to it.
[step]
--
cloneRepository("", "https://github.com/devonfw-tutorials/tutorial-compiler.git")
--
====

====
Switch to the 'tutorials'-repository and repeat all the previous steps:

https://github.com/devonfw-tutorials/tutorials.git

- Fork the 'tutorials'-repository
- Copy the 'tutorials'-URL

[step]
--
cloneRepository("", "https://github.com/devonfw-tutorials/tutorials.git")
--
After this step you should have both repositories in the same folder next to each other.
====

[step]
--
npmInstall("", {"name": "typescript", "global": true})
--

[step]
--
npmInstall("tutorial-compiler")
--

# Write the my-thai-star tutorial

Let's start with the second part of this tutorial and write the "my-thai-star" tutorial.

[step]
--
createFile("tutorials/my-thai-star/index.asciidoc")
--

Add the tutorial title "My Thai Star"
[step]
--
changeFile("tutorials/my-thai-star/index.asciidoc", {"content": "= My Thai Star"})
--

You have to write the introduction in between these equal signs '====' and underneath the title. 

[step]
--
changeFile("tutorials/my-thai-star/index.asciidoc", {"file": "text/intro.txt", "placeholder": "= My Thai Star" })
--

====
Last but not least add all the needed functions for this tutorial.
[step]
--
changeFile("tutorials/my-thai-star/index.asciidoc", {"file": "text/functions.txt", "placeholder": "This is the online demo of https://github.com/devonfw/my-thai-star" })
--

Follow the link below to find a list of all available functions and their descriptions
https://github.com/devonfw-tutorials/tutorial-compiler/wiki/Functions

====