= Bootstrap your devonfw development environment
====
devonfw offers complete IDE solution integrated with a lot​ of integrated tooling and initial settings​. 
It massively speeds up development, reduces risks and helps deliver better results.

## Prerequisites
* User should have a prior experience with Eclipse or any ide. 

## Learning goals
1. After completing this scenario, you will have learned how to install devonfw development environment i.e., the devonfw IDE.


More information about devonfw IDE can be found on https://devonfw.com/website/pages/docs/devonfw-ide-introduction.asciidoc.html
====
====
Follow the below steps to setup your devonfw development environment.
[step]
--
installDevonfwIde(["java","mvn"])
--
devonfw-ide is installed successfully with Maven and Java too. These tools can be customized by changing the configuration
in devon.properties.

More information on devonfw-ide can be found at https://devonfw.com/website/pages/docs/devonfw-ide-introduction.asciidoc.html
====