= Tutorial for the devon4j architecture
====

This tutorial aims to explain concepts and principles of devon4j architecture with help of an example.
After completeing this tutorial you will be aware of devon4j structure and architecture. 

====
====
### Step1 : Install devonfw-ide

To create devon4j application it is necessary to have devonfw-ide installed on your machine.For this tutorial purpose we will have it installed here.

If you want to try it on local machine you can refer [here](https://devonfw.com/website/pages/docs/devonfw-ide-introduction.asciidoc.html#setup.asciidoc).

[step]
--
installDevonfwIde(["java","mvn","vscode"])
--
Before proceeding to next steps make sure ide is installed.
====
====
### Step2: Create devon4j sample application

Once devonfw-ide is installed , we will create sample devon4j application with name *sampleapp*. 

If you want to create devon4j application on your local there are two ways to do it:
* In eclipse as shown [here](https://devonfw.com/website/pages/docs/devon4j.asciidoc_tutorials.html#tutorial-newapp.asciidoc_from-eclipse)
* Using command line as shown [here](https://devonfw.com/website/pages/docs/devon4j.asciidoc_tutorials.html#tutorial-newapp.asciidoc_from-command-line)

[step]
--
createDevon4jProject("sampleapp")
--

Once project is created switch to next tab of IDE. In IDE explorer you can see folder structure like devonfw-> workspaces->main->sampleapp . In sampleapp modules such as api,core and server will get created.

====

[step]
--
nextKatacodaStep("devon4j application architecture", [{ "image": "images/devon4j_proj_structure.jpg" }])
--

[step]
--
nextKatacodaStep("Step 3: Understand devon4j application architecture", [{ "file": "devon4j-app-arch.md" }])
--