= Tutorial for the devon4j architecture
====
There are many different views that are summarized by the term architecture. First, we will introduce the key principles and architecture principles of devonfw. Then, we will go into details of the the architecture of an application.

== Key Principles
For devonfw we follow these fundamental key principles for all decisions about architecture, design, or choosing standards, libraries, and frameworks:

* *KISS* +
Keep it small and simple
* *Open* +
Commitment to open standards and solutions (no required dependencies to commercial or vendor-specific standards or solutions)
* *Patterns* +
We concentrate on providing patterns, best-practices and examples rather than writing framework code.
* *Solid* +
We pick solutions that are established and have been proven to be solid and robust in real-live (business) projects.

== Architecture Principles
Additionally we define the following principles that our architecture is based on:
====

Install devonfw ide.
[step]
--
restoreDevonfwIde(["java", "mvn"])
--