= devon4j architecture in practice
====

## Prerequisites

Java programming knowledge

## Learning goals

This tutorial aims to explain concepts and principles of devon4j architecture with help of an sample application named JumpTheQueue. Below are the steps we will go through to understand it clearly.

* Clone JumpTheQueue repository
* Understand devon4j application structure 
* Understand Key and architectural principles followed by devon4j
* Understand devon4j application architecture

By end of this tutorial you will have detailed understanding of principles followed by devon4j application as well as its structure and architecture. 

====
====
We will start by setting up development environment.
[step]
--
restoreDevonfwIde(["java", "vscode"])
--
First, clone the Jump-The-Queue Repository.
[step]
--
cloneRepository("", "https://github.com/devonfw/jump-the-queue.git")
--

Once project is cloned switch to next tab of IDE. In IDE explorer you will be able to see folder structure like devonfw-> workspaces->main->jump-the-queue-> java->jtqj 
====
