= devon4j application generation
====
devon4j is the Java stack of devonfw. It allows you to build business applications (backends) using Java technology in a highly efficient and standardized way based on established best-practices.

More information about devon4j on https://devonfw.com/website/pages/docs/devon4j.asciidoc.html

== Project structure
The structure of a devon4j application is divided into the following modules:

api: module containing the API of your application. The API contains the required artifacts to interact with your application via remote services. This can be REST service interfaces, transfer-objects with their interfaces and datatypes but also OpenAPI or gRPC contracts.

core: maven module containing the core of the application with service implementation, as well as entire logic layer and dataaccess layer.

batch: optional module for batch layer

server: module that bundles the entire app (core with optional batch) typically as a bootified WAR file.

====

To use the devon4j you first have to install the devonfw ide. 
[step]
--
restoreDevonfwIde(["java","mvn"])
--

Now you are ready to create your first project
[step]
--
createDevon4jProject("cobigenexample")
--

Build the java project
[step]
--
buildJava("cobigenexample", false)
--

