= Tutorial for the Jump The Queue Application
====
Jump The Queue is a small application based on the devonfw framework, which you can create yourself by following our simple step-by-step tutorial. By doing so, you will learn about the app development workflow and gain insight into the design of a professional business information system.

More information about Jump The Queue on https://github.com/devonfw/jump-the-queue
====

Install devonfw IDE
[step]
--
installDevonfwIde(["java", "mvn", "node", "ng", "npm"])
--

Clone the Jump-The-Queue Repository.
[step]
--
cloneRepository("", "https://github.com/devonfw/jump-the-queue.git")
--

====
[step]
== Build and Run Java Server
--
buildJava("jump-the-queue/java/jtqj", true)
runServerJava("jump-the-queue/java/jtqj/server", { "startupTime": 40, "port": 8081, "path": "jumpthequeue" })
--
Now the Java Server should be running.
====

====
Now build and run the Angular Frontend Server. For that you need to install the dependencies first.
[step]
== Serve the Frontend Server
--
npmInstall("jump-the-queue/angular")
runClientNg("jump-the-queue/angular", { "startupTime": 200, "port": 4200, "path": "" })
--
Now the Angular Frontend Server should be running.
====

