= Jump start an end-to-end devonfw sample application.
====
Jump The Queue is a small application based on the devonfw framework, which you can create yourself by following our simple step-by-step tutorial. By doing so, you will learn about the app development workflow and gain insight into the design of a professional business information system.

## Prerequisites
* User should have Java, Angular development experience

## Learning goals
* How to create devonfw sample application Jump-The-Queue
* The Architecture of the application. 

More information about Jump The Queue on https://github.com/devonfw/jump-the-queue
====

[step]
--
restoreDevonfwIde(["java", "mvn", "node", "ng", "npm"])
--

Note: Setup script can take some time for setup.

First, clone the Jump-The-Queue Repository.
[step]
--
cloneRepository("Clone Jump The Repository", "https://github.com/devonfw/jump-the-queue.git")
--

====
[step]
== Build and Run Java Server
--
buildJava("jump-the-queue/java/jtqj", true)
runServerJava("jump-the-queue/java/jtqj/server", { "startupTime": 40, "port": 8081, "path": "jumpthequeue" })
--
This will take some time

Now the Java Server should be running.
====

Install dependencies before you build and run frontend server.

[step]
--
npmInstall("jump-the-queue/angular")
--

====
Now build and run the Angular Server.
The following two steps are only needed in this tutorial. Normally you can simply execute "ng serve", open the https://localhost:4200/ and start using the app.

In the next step you need to change the Base URL for the REST Services. 
[step]
== Serve the Frontend Server
--
changeFile("jump-the-queue/angular/src/environments/environment.ts", {"content": "https://[[HOST_SUBDOMAIN]]-8081-[[KATACODA_HOST]].environments.katacoda.com/jumpthequeue/services/rest", "placeholder": "http://localhost:8081/jumpthequeue/services/rest"})
runClientNg("jump-the-queue/angular", { "startupTime": 200, "port": 4200, "path": "" })
--
Now the Angular Frontend Server should be running.
====
[step]
--
nextKatacodaStep("Conclusion", [{ "file": "files/conclusion.md" }])
--
