= Cobigen Setup

====
CobiGen is a generic incremental code generator. It allows you build Java CRUD application based on the devonfw architecture including all software layers. You can generate all necessary classes and services (DAOs, Transfer Objects, simple CRUD use cases with REST services) of the application from one single entity class.

CobiGen provides Maven and Eclipse integrations. But there is also a command line interface (CLI) which enables the generation of code using only few commands.

More information about CobiGen on https://devonfw.com/website/pages/docs/master-cobigen.asciidoc.html
====

To use the cobigen cli you first have to install the devonfw ide. You will find more information about devonfw on https://devonfw.com/website/pages/welcome/welcome.html.


====

Current versions:

CobiGen - Eclipse Plug-in v7.0.0

CobiGen - Maven Build Plug-in v7.0.0

CobiGen CLI v1.2.0

CobiGen v7.0.0

CobiGen - Java Plug-in v7.0.0

CobiGen - XML Plug-in v7.0.0

CobiGen - TypeScript Plug-in v7.0.0

CobiGen - Property Plug-in v7.0.0

CobiGen - Text Merger v7.0.0

CobiGen - JSON Plug-in v7.0.0

CobiGen - HTML Plug-in v7.0.0

CobiGen - Open API Plug-in v7.0.0

CobiGen - FreeMaker Template Engine v7.0.0

CobiGen - Velocity Template Engine v7.0.0

====

