= A setup tutorial for devonfw Code-based incremental Generator(i.e. Cobigen)
====
CobiGen is a generic incremental code generator. It allows you to build Java CRUD application based on the devonfw architecture including all software layers. You can generate all necessary classes and services (DAOs, Transfer Objects, simple CRUD use cases with REST services) of the application from one single entity class.

There is Cobigen Command Line Interface( Cobigen CLI) where we can start the setup following the generation of code. There are various commands provided using which we can proceed with code generation.

Here in this tutorial we will learn the following:
-Cobigen setup
-CLI Commands 
-Cobigen with Eclipse integration
====

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--

====
# Prerequisites
Before we start, the installation of devonfw ide is already done for you.
Now we will proceed with CobiGen installation.

[step]
--
nextKatacodaStep("CLI Execution steps", [{ "file": "files/cliExecutionCommands.md" }])
--

In next step we will go through some implementaion of commands used in Cobigen CLI.
====


====
Below are the commands which we can use on CobiGen CLI.

Using the following command and option you will be able to customize your generation.

[step]
--
nextKatacodaStep("Commands and Options", [{ "file": "files/commandsAndOptions.md" }])
--

To get more information about Troubleshooting in CLI visit on https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_cobigen-cli.html#howto_cobigen-cli-generation.asciidoc_troubleshooting

Now in the next step we will see how we can integrate CobiGen in eclipse.
====


Remark: CobiGen is preinstalled in the devonfw/devon-ide.

1.1  Preconditions
    - Eclipse 4.x

    - Java 7 Runtime (for starting eclipse with CobiGen). This is independent from the target version of your developed code

1.2. Installation steps
    1. Open the eclipse installation dialog
    menu bar → Help → Install new Software
[step]
--
nextKatacodaStep("Installation", [{"image": "images/01-install-new-software.png"}])
-- 

====
Here we can select the updates.
    2. Open CobiGen’s update site

[step]
--
nextKatacodaStep("Select Update Site", [{"image": "images/02-select-update-site.png"}, { "file": "files/eclipseIntegration.md" }])
-- 

Now you can start generating. To get an introduction of CobiGen try the devon4j templates and work on the devon4j sample application.
====

In this step we will learn about the types of modes for usage of CobiGen.

CobiGen has two different generation modes depending on the input selected for generation. 
    1. Simple mode
    2. Batch mode

[step]
--
nextKatacodaStep("1. Simple mode usage", [{ "file": "files/simpleModeUsage.md" }, {"image": "images/03-simple-mode-usage.png"}])
--

[step]
--
nextKatacodaStep("2. Batch mode usage", [{ "file": "files/batchModeUsage.md" }, {"image": "images/04-batch-mode-usage.png"}])
--

[step]
--
nextKatacodaStep("Conclusion", [{ "file": "files/conclusion.md" }])
--