= Tutorial for Cobigen Setup
====
CobiGen is a generic incremental code generator. It allows you to build Java CRUD application based on the devonfw architecture including all software layers. You can generate all necessary classes and services (DAOs, Transfer Objects, simple CRUD use cases with REST services) of the application from one single entity class.

CobiGen provides Maven and Eclipse integrations. But there is also a command line interface (CLI) which enables the generation of code using only few commands.

More information about CobiGen on https://devonfw.com/website/pages/docs/master-cobigen.asciidoc.html
====

Current versions:

CobiGen - Eclipse Plug-in v7.0.0

CobiGen - Maven Build Plug-in v7.0.0

CobiGen CLI v1.2.0

CobiGen v7.0.0

CobiGen - Java Plug-in v7.0.0

CobiGen - XML Plug-in v7.0.0

CobiGen - TypeScript Plug-in v7.0.0

CobiGen - Property Plug-in v7.0.0

CobiGen - Text Merger v7.0.0

CobiGen - JSON Plug-in v7.0.0

CobiGen - HTML Plug-in v7.0.0

CobiGen - Open API Plug-in v7.0.0

CobiGen - FreeMaker Template Engine v7.0.0

CobiGen - Velocity Template Engine v7.0.0

To start with Cobigen setup tutorial. You first need to have devonIde already installed.

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--

 Now you have devonIde installed.

 1. Before proceeding with setup. Have a look at feature and characteristics of cobigen.

 2. Generate fresh files across all the layers of a application - ready to run.

3. Add on to existing files merging code into it. E.g. generate new methods into existing java classes or adding nodes to an XML file. Merging of contents into existing files will be done using structural merge mechanisms.

4. Structural merge mechanisms are currently implemented for Java, XML, Java Property Syntax, JSON, Basic HTML, Text Append, TypeScript.

5. Conflicts can be resolved individually but automatically by former configuration for each template.

6. CobiGen provides an Eclipse integration as well as a Maven Integration.

7. CobiGen comes with an extensive documentation for users and developers.

8. Templates can be fully tailored to project needs - this is considered as a simple task.

====
Now we will proceed with Cobigen installation.
[step]
--
createFolder("Desktop/cobigen")
--