= Setting up devonfw Code Generator(i.e. CobiGen)
====
CobiGen is a generic incremental code generator. It allows you to generate application code based on the devonfw architecture including all software layers. 
There is also a CobiGen Command Line Interface(CLI) where we can start the setup following the generation of code. 

This tutorial mainly focuses on the setup of CobiGen along with various commands to execute the generations.
## Prerequisites
* devonfw IDE
* User should have development experience of any language.

## Learning goals.
Here in this tutorial you will learn 
* To setup CobiGen 
* To use commands on CobiGen CLI  
* To integrate Eclipse with CobiGen
====

[step]
--
restoreDevonfwIde(["java","mvn"], "2020.08.001")
--

====
devonfw IDE has been installed for you.

[step]
--
nextKatacodaStep("CobiGen Setup", [{ "file": "files/cobiGenSetup.md" }])
--

In next step we will go through some implementation of CLI commands.
====


====

In this step, you will learn CobiGen commands.

[step]
--
nextKatacodaStep("CobiGen CLI Commands and Options", [{ "file": "files/commandsAndOptions.md" }])
--

Now in the next step we will see how we can integrate CobiGen with eclipse.
====


Note: CobiGen comes preinstalled with devonfw IDE.

1.1  Preconditions
    - Eclipse 4.x

    - Atleast Java 7 Runtime (for starting eclipse with CobiGen). This is independent from the target version of your developed code

1.2. Installation steps
    * Open the eclipse installation dialog
    menu bar → Help → Install new Software
[step]
--
nextKatacodaStep("Integrate Eclipse with CobiGen", [{"image": "images/01-install-new-software.png"}])
-- 

====
Here we can select the updates.
    2. Open CobiGen’s update site

[step]
--
nextKatacodaStep("Select Update Site", [{"image": "images/02-select-update-site.png"}, { "file": "files/eclipseIntegration.md" }])
-- 

Now you can start generating. To get an introduction of CobiGen try the devon4j templates and work on the devon4j sample application.
====


[step]
--
nextKatacodaStep("CobiGen Usage - Simple Mode", [{ "file": "files/simpleModeUsage.md" }, {"image": "images/03-simple-mode-usage.png"}])
--

[step]
--
nextKatacodaStep("CobiGen Usage - Batch Mode", [{ "file": "files/batchModeUsage.md" }, {"image": "images/04-batch-mode-usage.png"}])
--

[step]
--
nextKatacodaStep("Conclusion", [{ "file": "files/conclusion.md" }])
--