= Setting up devonfw Code Generator(i.e. CobiGen)

[tags]
--
technology=CobiGen;Eclipse
difficulty=beginner
topic=setup
asset=CobiGen
--

====
CobiGen is a generic incremental code generator. It allows you to generate application code based on the devonfw architecture including all software layers. 
There is also a CobiGen Command Line Interface(CLI) where you can start the setup following the generation of code. 

This tutorial mainly focuses on the setup of CobiGen along with various commands to execute the generations.
## Prerequisites
* devonfw IDE
* User should have development experience of any language.

## Learning goals.
Here in this tutorial you will learn 
* To setup CobiGen 
* To use commands on CobiGen CLI  
* To integrate Eclipse with CobiGen
====

[step]
--
restoreDevonfwIde(["java","mvn"])
--

====
devonfw IDE has been installed for you.

[step]
--
displayContent("CobiGen Setup", [{ "file": "files/cobiGenSetup.md" }])
--

In next step, you will learn about CobiGen CLI commands.
====


====

In this step, you will learn CobiGen commands.

[step]
--
displayContent("CobiGen CLI Commands and Options", [{ "file": "files/commandsAndOptions.md" }])
--

In next step, you will learn about how to integrate CobiGen with Eclipse.
====


Note: CobiGen comes preinstalled with devonfw IDE.

1.1  Preconditions
    - Eclipse 4.x

    - Atleast Java 7 Runtime (for starting eclipse with CobiGen). This is independent from the target version of your developed code

1.2. Installation steps
    * Open the eclipse installation dialog
    menu bar → Help → Install new Software
[step]
--
displayContent("Integrate Eclipse with CobiGen", [{"image": "images/01-install-new-software.png"}])
-- 

====
Here you can select the updates.
    2. Open CobiGen’s update site

[step]
--
displayContent("Select Update Site", [{"image": "images/02-select-update-site.png"}, { "file": "files/eclipseIntegration.md" }])
-- 

* Checkout (clone) your project’s templates folder or use the current templates released with CobiGen (https://github.com/devonfw/cobigen/tree/master/cobigen-templates) and then choose 
Import -> General -> Existing Projects into Workspace to import the templates into your workspace.
====


[step]
--
displayContent("CobiGen Usage - Simple Mode", [{ "file": "files/simpleModeUsage.md" }, {"image": "images/03-simple-mode-usage.png"}])
--

[step]
--
displayContent("CobiGen Usage - Batch Mode", [{ "file": "files/batchModeUsage.md" }, {"image": "images/04-batch-mode-usage.png"}])
--

[step]
--
displayContent(" ", [{ "file": "files/healthCheckTroubleshooting-Conclusion.md" }])
--
