= Create a CRUD Python Flask application using CobiGen's OpenAPI plugin
====

[step]
--
installDevonfwIde(["java","mvn"])
installCobiGen()
executeCommand("devon","devon")
-- 

[step]
--
adaptTemplatesCobiGen()
executeCommand("cd /root/.cobigen/templates/CobiGen_Templates/src/main/templates","cd /root/.cobigen/templates/CobiGen_Templates/src/main/templates")
cloneRepository("", "https://github.com/devonfw-forge/cobigen-python-templates.git")
--

[step]
--
createFile("context.xml", {"file": "files/context.xml"})
--

[step]
--
executeCommand("cd /root/devonfw/workspaces/main","cd /root/devonfw/workspaces/main")
createFile("cobigen-python-example/user.yml", "files/user.yml")
--

[step]
--
executeCommand("cobigen generate user.yml -i 1","cobigen generate user.yml -i 1",{"dir":"cobigen-python-example"})
--

[step]
--
executeCommand("python3 -m pip install virtualenv","python3 -m pip install virtualenv")
executeCommand("python3 -m virtualenv venv","python3 -m virtualenv venv")
executeCommand("activate.ps1","source activate", {"dir":"venv/bin"} )
executeCommand("cd /root/devonfw/workspaces/main/cobigen-python-example","cd /root/devonfw/workspaces/main/cobigen-python-example")
executeCommand("pip install -r requirements.txt","pip install -r requirements.txt")
--

[step]
--
executeCommand("flask db init","flask db init")
nextKatacodaStep("Initial commit", [{ "file": "files/initialCommit.md" }])
executeCommand("flask db upgrade","flask db upgrade")
--

[step]
--
executeCommand("flask run","flask run")
nextKatacodaStep("Postman test", [{ "file": "files/postmanTest.md" }])
--  

